CREATE TABLE Patient (
    patient_id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    full_name VARCHAR(50) NOT NULL,

    email VARCHAR(100) NOT NULL UNIQUE
        CHECK (
            email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
        ),

    password VARCHAR(50) NOT NULL
        CHECK (
            LENGTH(password) >= 8
            AND password ~ '[A-Z]'      -- At least one uppercase letter
            AND password ~ '[a-z]'      -- At least one lowercase letter
            AND password ~ '[0-9]'      -- At least one number
            AND password ~ '[^A-Za-z0-9]' -- At least one special character
        ),

    phone VARCHAR(20),

    date_of_birth DATE NOT NULL,

    sex VARCHAR(10)
        CHECK (sex IN ('Male', 'Female')),

    address TEXT,

    patient_type TEXT NOT NULL
        CHECK (patient_type IN ('student', 'staff')),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Student (
    patient_id int8 PRIMARY KEY
  
        REFERENCES Patient(patient_id)
        ON DELETE CASCADE,

    student_number VARCHAR(20) UNIQUE NOT NULL,
    faculty VARCHAR(100) NOT NULL,
    year_of_study INT NOT NULL
);

CREATE TABLE Staff (
    patient_id int8 PRIMARY KEY
        REFERENCES Patient(patient_id)
        ON DELETE CASCADE,

    staff_number VARCHAR(20) UNIQUE NOT NULL,
    department VARCHAR(100),
    job_title VARCHAR(100)
);

 update Employee(
   employee_id int8 UNIQUE PRIMARY KEY,
   full_name varchar(50) NOT NULL,
   email VARCHAR(100) NOT NULL UNIQUE
        CHECK (
            email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
        ),
   employee_type varchar(50) NOT NULL
         CHECK (employee_type IN ('Nurse', 'Admin')),
    password VARCHAR(50) NOT NULL
        CHECK (
            LENGTH(password) >= 8
            AND password ~ '[A-Z]'      -- At least one uppercase letter
            AND password ~ '[a-z]'      -- At least one lowercase letter
            AND password ~ '[0-9]'      -- At least one number
            AND password ~ '[^A-Za-z0-9]' -- At least one special character
        )
);

CREATE TABLE appointment (
    appointment_id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    patient_id int8 NOT NULL
        REFERENCES Patient(patient_id)
        ON DELETE CASCADE,

    service VARCHAR(50) NOT NULL,

    appointment_date DATE NOT NULL,

    appointment_time TIME NOT NULL
);

CREATE TABLE Inventory (
    inventory_id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    quantity INT NOT NULL,
    expiry_date date NOT NULL,

    updated_by BIGINT REFERENCES Employee(employee_id),

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Sensor_log (
    sensor_log_id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    patient_id int8
        REFERENCES Patient(patient_id)
        ON DELETE SET NULL,

    scanned_number VARCHAR(20) NOT NULL,

    detected_type TEXT
        CHECK (detected_type IN ('student', 'staff')),

    scan_status TEXT NOT NULL
        CHECK (scan_status IN ('success', 'not_found', 'error')),

    confidence_score DECIMAL(5,2),

    image_path TEXT,

    scanned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE Visit (
    visit_id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    patient_id BIGINT NOT NULL
        REFERENCES Patient(patient_id)
        ON DELETE CASCADE,

    visit_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    reason_for_visit TEXT NOT NULL,
    diagnosis TEXT,
    treatment_given TEXT,
    notes TEXT
);
